new = {'files_paths\\1_tera_animes.txt': {'clips path': 'H:Anime_1Tera',
                                    'dir tag': '1 tera animes',
                                    'file type': 'anime',
                                    'hard disk': '1 tera',
                                    'serial number': '1AEA6007'},
 'files_paths\\1_tera_courses.txt': {'clips path': 'H:Courses',
                                     'dir tag': '1 tera courses',
                                     'file type': 'course',
                                     'hard disk': '1 tera',
                                     'serial number': '1AEA6007'},
 'files_paths\\1_tera_movies.txt': {'clips path': 'H:Movies_1Tera',
                                    'dir tag': '1 tera movies',
                                    'file type': 'movie',
                                    'hard disk': '1 tera',
                                    'serial number': '1AEA6007'},
 'files_paths\\1_tera_tv.txt': {'clips path': 'H:TV Series_1Tera',
                                'dir tag': '1 tera tv',
                                'file type': 'tv series',
                                'hard disk': '1 tera',
                                'serial number': '1AEA6007'},
 'files_paths\\2_tera_animes.txt': {'clips path': 'Anime_2Tera',
                                    'dir tag': '2 tera animes',
                                    'file type': 'anime',
                                    'hard disk': '2 tera',
                                    'serial number': '6C8E2E75'},
 'files_paths\\2_tera_movies.txt': {'clips path': 'Movies_2Tera',
                                    'dir tag': '2 tera movies',
                                    'file type': 'movie',
                                    'hard disk': '2 tera',
                                    'serial number': '6C8E2E75'},
 'files_paths\\2_tera_tv.txt': {'clips path': 'TV Series_2Tera',
                                'dir tag': '2 tera tv',
                                'file type': 'tv series',
                                'hard disk': '2 tera',
                                'serial number': '6C8E2E75'},
 'files_paths\\books.txt': {'clips path': 'E:\\Books',
                            'dir tag': 'this pc books ',
                            'file type': 'book',
                            'hard disk': 'main',
                            'serial number': 'B0193957'},
 'files_paths\\main hard_e_tv_series.txt': {'clips path': 'E:/TV Series',
                                            'dir tag': 'this pc e',
                                            'file type': 'tv series',
                                            'hard disk': 'main',
                                            'serial number': 'B0193957'},
 'files_paths\\main hard_f_animes.txt': {'clips path': 'F:\\Anime',
                                         'dir tag': 'this pc f',
                                         'file type': 'anime',
                                         'hard disk': 'main',
                                         'serial number': 'A653ADC9'},
 'files_paths\\main hard_f_tv_series.txt': {'clips path': 'F:/TV Series',
                                            'dir tag': 'this pc f',
                                            'file type': 'tv series',
                                            'hard disk': 'main',
                                            'serial number': 'A653ADC9'},
 'files_paths\\main_hard_courses_f.txt': {'clips path': 'F:\\Courses',
                                          'dir tag': 'this pc courses',
                                          'file type': 'course',
                                          'hard disk': 'main',
                                          'serial number': 'A653ADC9'},
 'files_paths\\main_hard_movies_e.txt': {'clips path': 'E:/Movies(2)',
                                         'dir tag': 'this pc e',
                                         'file type': 'movie',
                                         'hard disk': 'main',
                                         'serial number': 'B0193957',},
 'files_paths\\main_hard_movies_f.txt': {'clips path': 'F:/Movies',
                                         'dir tag': 'this pc f',
                                         'file type': 'movie',
                                         'hard disk': 'main',
                                         'serial number': 'A653ADC9'},
 'files_paths\\toshiba_movies.txt': {'clips path': 'Movies',
                                     'dir tag': 'toshiba movies',
                                     'file type': 'movie',
                                     'hard disk': 'toshiba',
                                     'serial number': '03D08A60'},
 'files_paths\\toshiba_tv.txt': {'clips path': 'TV Series',
                                 'dir tag': 'toshiba tv',
                                 'file type': 'tv series',
                                 'hard disk': 'toshiba',
                                 'serial number': '03D08A60'}}


for k, v in new.items():
    print('hard disk: {}   serial: {}'.format(new[k]['dir tag'], new[k]['serial number']))